import {ATTR,SKILLS,PATHS,CLANS,VILLAGES,FEATS,JUTSU,NATURES} from './data.mjs';
export const DEFAULT={name:'',age:19,village:'Konoha',clan:'Clanlos',main:'nin',side:'sensor',nature:'Katon',extraNature:'Suiton',method:'array',base:{KRA:8,GES:14,KON:13,INT:16,WAH:10,WIL:12},bonusMode:'2+1',bonus:['INT','WIL','KON'],villageSkill:'Überzeugen',clanSkill:'Aufmerksamkeit',pathSkills:['Fingerzeichen','Ninja-Wissen','Nachforschen'],feats:['Chakra-Reservoir','Wachsam'],featSkill:'Handwerk',saveAttr:'KON',weapon:'Katana',puppet:false,jutsu:[],jin:false,biju:'Isobu',background:'Grenzkind',goal:'Anerkennung',bond:'Die Menschen meiner Heimat',bond2:'Meine selbst gewählte Aufgabe',scar:'',smallSchool:'Wald',status:'offiziell'};
export const BACKGROUNDS={Grenzkind:'Du kennst verlassene Straßen, Passierscheine und die Geräusche naher Gefechte.',Clanerbe:'Deine Familie hat Erwartungen an diese Prüfung.',Quereinsteiger:'Du hast später angefangen und kennst Arbeit außerhalb der Shinobi-Dörfer.',Feldhelfer:'Du hast Verwundete versorgt und gelernt, wann jemand Hilfe verbirgt.',Abtrünnig:'Eine örtliche Bürgschaft ermöglicht deine Teilnahme. Deine Dorfausbildung bleibt erhalten.'};
export const GOALS={Anerkennung:'Einen Platz durch deine eigenen Leistungen gewinnen.',Schutz:'Menschen schützen und dafür Einfluss erhalten.',Wahrheit:'Eine Spur zu einer verschwundenen Person verfolgen.',Freiheit:'Einen eigenen Vertrag erhalten und eine alte Verpflichtung lösen.'};
export const BIJU=['Shukaku','Matatabi','Isobu','Son Gokū','Kokuō','Saiken','Chōmei','Gyūki','Kurama'];
export const WEAPONS={Kunai:{dice:[1,4],range:6,far:18,finesse:true,price:100},Shuriken:{dice:[1,4],range:9,far:27,thrown:true,price:50},Senbon:{dice:[1,4],range:6,far:18,thrown:true,price:20},Tantō:{dice:[1,6],range:1.5,finesse:true,price:3000},Katana:{dice:[1,8],range:1.5,finesse:true,price:8000},Großschwert:{dice:[2,6],range:1.5,str:16,price:15000},Kusarigama:{dice:[1,6],range:3,finesse:true,price:5000},Kriegsfächer:{dice:[1,6],range:1.5,price:8000},Speer:{dice:[1,10],range:3,price:4000},Bō:{dice:[1,8],range:1.5,price:1000},Bogen:{dice:[1,8],range:45,far:180,dex:true,price:5000}};
export const mod=n=>Math.floor((n-10)/2);
export const hasPath=(c,p)=>c.main===p||c.side===p;
export const feat=(c,f)=>c.feats.includes(f);
export function stats(c){const a={...c.base}; if(c.bonusMode==='2+1'){a[c.bonus[0]]+=2;a[c.bonus[1]]++;}else c.bonus.forEach(k=>a[k]++);return a;}
export function natures(c){return [...new Set([...(c.clan==='Sarutobi'?[c.nature,'Katon']:CLANS[c.clan].natures||[c.nature]),...(feat(c,'Elementarwandler')?[c.extraNature]:[])])];}
export function skills(c){return [...new Set(['Chakra-Kontrolle',c.villageSkill,c.clanSkill,...c.pathSkills,...(feat(c,'Giftmischer')?[c.featSkill]:[])])];}
export function derived(c){const a=stats(c),m=Object.fromEntries(ATTR.map(k=>[k,mod(a[k])]));const path=PATHS[c.main];return {a,m,pb:2,level:3,hp:path.die+m.KON+2*(path.die/2+1+m.KON)+(c.village==='Iwa'?3:0)+(feat(c,'Zäh')?6:0),cp:Math.max(1,6+m.KON+m.WIL)+2*Math.max(1,3+m.WIL)+(c.clan==='Uzumaki'?3:0)+(c.jin?3:0)+(feat(c,'Chakra-Reservoir')?6:0),ak:10+m.GES+(c.main==='tai'?2:1),initiative:m.GES+(feat(c,'Wachsam')?3:0),jAtk:2+m[path.attr],sg:10+m[path.attr],genSG:10+m[path.attr]+(hasPath(c,'gen')?1:0),saves:[...new Set([...path.saves,...(feat(c,'Geübte Abwehr')?[c.saveAttr]:[])])],skills:skills(c),nature:natures(c),passive:10+m.WAH+(skills(c).includes('Aufmerksamkeit')?2:0)};}
export function access(c,j){const z=j.Zugang; const n=natures(c); if(!['E','D','C','D–S'].includes(j.Rang))return false;
 if(z.includes('Grundtechnik')||z.startsWith('Allgemein'))return true;
 if(z.includes('Aufklärer-Ausbildung')&&hasPath(c,'sensor'))return true;
 if(z.includes('Tiervertrag'))return hasPath(c,'summon');
 if(z.includes('Kage Bunshin')||z.includes('Mangekyō')||z.includes('Gaara')||z.includes('Sand'))return false;
 if(z.includes('Hyūga'))return c.clan==='Hyūga';
 if(z.includes('Inuzuka'))return c.clan==='Inuzuka';
 for(const [str,clan] of [['Nara','Nara'],['Yamanaka','Yamanaka'],['Akimichi','Akimichi'],['Aburame','Aburame'],['Hōzuki','Hōzuki'],['Mokuton','Mokuton'],['Hyōton','Yuki'],['Kaguya','Kaguya'],['Bakuton','Bakuton']])if(z.includes(str))return c.clan===clan;
 if(z.includes('Genjutsu'))return hasPath(c,'gen')||c.clan==='Uchiha';
 if(z.includes('Iryō'))return hasPath(c,'med')||(z.includes('Giftmischer')&&feat(c,'Giftmischer'));
 if(z.includes('Taijutsu'))return hasPath(c,'tai')&&( !z.includes('Tor 1')||c.main==='tai');
 if(z.includes('Fūinjutsu'))return hasPath(c,'fu')||(c.clan==='Uzumaki'&&j.Rang==='D');
 if(z.includes('Sharingan'))return c.clan==='Uchiha';
 for(const el of NATURES)if(z.includes(el))return n.includes(el);
 return false;
}
const isElement=j=>NATURES.some(n=>j.Gruppe.includes(n));
export function slots(c){let s=[{key:'start1',label:'Starttechnik 1',ranks:['E','D']},{key:'start2',label:'Starttechnik 2',ranks:['E','D']},{key:'start3',label:'Starttechnik 3',ranks:['E','D']},{key:'level2',label:'Aufstieg auf Stufe 2',ranks:['E','D']},{key:'level3',label:'Aufstieg auf Stufe 3',ranks:['E','D','C']}];
 if(c.main==='nin')s.push({key:'nin',label:'Elementarfokus',ranks:['D'],filter:j=>isElement(j)});
 if(c.main==='gen')for(let i=0;i<2;i++)s.push({key:'gen'+i,label:'Trugbild '+(i+1),ranks:['D'],filter:j=>j.Gruppe.includes('Genjutsu')});
 if(c.side==='gen')s.push({key:'sidegen',label:'Nebenweg Genjutsu',ranks:['D'],filter:j=>j.Gruppe.includes('Genjutsu')});
 if(c.main==='fu')for(let i=0;i<2;i++)s.push({key:'fu'+i,label:'Siegelschreiber '+(i+1),ranks:['D'],filter:j=>j.Gruppe.includes('Fūinjutsu')});
 if(c.side==='fu')s.push({key:'sidefu',label:'Nebenweg Siegelkunst',ranks:['D'],filter:j=>j.Gruppe.includes('Fūinjutsu')});
 if(c.clan==='Sarutobi')s.push({key:'sarutobi',label:'Feuerschule',ranks:['D'],filter:j=>j.Gruppe.includes('Katon')});
 if(feat(c,'Elementarwandler'))s.push({key:'extra',label:'Elementarwandler',ranks:['D'],filter:j=>j.Gruppe.includes(c.extraNature)});
 return s;
}
export function options(c,slot){return JUTSU.filter(j=>access(c,j)&&slot.ranks.includes(j.Rang)&&(!slot.filter||slot.filter(j))&&!j.Zugang.includes('Grundtechnik')&&!j.Zugang.includes('Wegmerkmal'));}
export function known(c){let ids=['j001','j002','j003','j004',...Object.values(c.jutsu||{})];if(hasPath(c,'summon'))ids.push('j010');if(hasPath(c,'med'))ids.push(JUTSU.find(j=>j.Name.startsWith('Shōsen Jutsu')).id);if(c.clan==='Hōzuki')ids.push(JUTSU.find(j=>j.Name.startsWith('Hydrifikation')).id);return [...new Set(ids.filter(Boolean))];}
export function autoTech(c){let used=new Set(),selected={};for(const s of slots(c).sort((a,b)=>options(c,a).length-options(c,b).length)){let opts=options(c,s).filter(j=>!used.has(j.id));let prefer=c.main==='tai'?['Dynamischer','Blätterwirbel','Körperflimmern','Seilbefreiung','Löwenkombo']:['Körperflimmern','Kleines Wassergeschoss','Phönixblumen','Seilbefreiung','Blitzkugel','Höllenvision'];let j=opts.find(j=>prefer.some(p=>j.Name.includes(p)))||opts[0];if(j){selected[s.key]=j.id;used.add(j.id);}}return selected;}
export function normalize(c){c=structuredClone(c);if(c.clan==='Sarutobi'&&c.nature==='Katon')c.nature='Suiton';if(c.main===c.side)c.side=Object.keys(PATHS).find(p=>p!==c.main);c.feats=c.feats.slice(0,c.clan==='Clanlos'?2:1);if(!c.feats.length)c.feats=['Chakra-Reservoir'];while(c.feats.length<(c.clan==='Clanlos'?2:1))c.feats.push(c.feats.includes('Wachsam')?'Zäh':'Wachsam');if(!VILLAGES[c.village].skills.includes(c.villageSkill))c.villageSkill=VILLAGES[c.village].skills[0];if(!CLANS[c.clan].skills.includes(c.clanSkill)&&!CLANS[c.clan].skills.includes(c.villageSkill))c.clanSkill=CLANS[c.clan].skills[0];if(c.clanSkill===c.villageSkill)c.clanSkill=Object.keys(SKILLS).find(k=>k!=='Chakra-Kontrolle'&&k!==c.villageSkill);let used=new Set(['Chakra-Kontrolle',c.villageSkill,c.clanSkill]);c.pathSkills=c.pathSkills.filter(s=>PATHS[c.main].skills.includes(s)&&!used.has(s));c.pathSkills.forEach(s=>used.add(s));for(const s of PATHS[c.main].skills)if(c.pathSkills.length<3&&!used.has(s)){c.pathSkills.push(s);used.add(s);}if(!hasPath(c,'ken'))c.puppet=false;if(feat(c,'Giftmischer')&&used.has(c.featSkill))c.featSkill=Object.keys(SKILLS).find(k=>!used.has(k));return c;}
export function validate(c){let errors=[];if(!c.name.trim())errors.push('Gib deiner Figur einen Namen.');if(!Number.isInteger(+c.age)||+c.age<16||+c.age>80)errors.push('Die Ausschreibung richtet sich an erwachsene und fast erwachsene Shinobi (16–80).');const vals=Object.values(c.base);if(c.method==='array'&&[...vals].sort((a,b)=>a-b).join()!=='8,10,12,13,14,16')errors.push('Verteile jeden Wert der Standardreihe genau einmal.');const cost={8:0,9:1,10:2,11:3,12:4,13:5,14:7,15:9,16:12};if(c.method==='points'&&(vals.some(x=>cost[x]===undefined)||vals.reduce((n,x)=>n+cost[x],0)>30))errors.push('Punktekauf: höchstens 30 Punkte, Werte von 8 bis 16.');const bonuses=c.bonus.slice(0,c.bonusMode==='2+1'?2:3);if(new Set(bonuses).size!==bonuses.length)errors.push('Herkunftsboni müssen verschiedene Attribute erhöhen.');if(Object.values(stats(c)).some(x=>x>18))errors.push('Startwerte sind auf 18 begrenzt.');if(feat(c,'Elementarwandler')&&(CLANS[c.clan].natures||[c.nature]).includes(c.extraNature))errors.push('Elementarwandler benötigt eine zusätzliche, andere Natur.');if(c.main===c.side)errors.push('Wähle zwei verschiedene Wege.');if(new Set(c.feats).size!==c.feats.length)errors.push('Ein Talent kann nur einmal gewählt werden.');if(feat(c,'Geübte Abwehr')&&PATHS[c.main].saves.includes(c.saveAttr))errors.push('Geübte Abwehr benötigt einen bisher ungeübten Rettungswurf.');const all=['Chakra-Kontrolle',c.villageSkill,c.clanSkill,...c.pathSkills,...(feat(c,'Giftmischer')?[c.featSkill]:[])];if(new Set(all).size!==all.length)errors.push('Wähle für doppelte Fertigkeiten einen zulässigen Ersatz.');if(c.pathSkills.length!==3)errors.push('Wähle drei Fertigkeiten deines Hauptwegs.');let selected=[];for(const s of slots(c)){let id=c.jutsu?.[s.key];if(!options(c,s).some(j=>j.id===id))errors.push('Wähle eine erlaubte Technik für '+s.label+'.');if(selected.includes(id))errors.push('Jede gelernte Technik muss verschieden sein.');selected.push(id);}if(hasPath(c,'ken')&&!c.puppet&&WEAPONS[c.weapon].price>8000)errors.push('Die Start-Signaturwaffe darf höchstens 8.000 Ryō kosten.');if(c.jin&&!BIJU.includes(c.biju))errors.push('Wähle deinen Bijū.');return [...new Set(errors)];}
export function skillBonus(c,name){const d=derived(c);return (d.m[SKILLS[name]||name]||0)+(d.skills.includes(name)?2:0);}
export const shortName=j=>j.Name.match(/\(([^()]*)\)$/)?.[1]||j.Name;
