'use client';
import {Select,SelectTrigger,SelectValue,SelectContent,SelectItem} from '@/components/ui/select';
import {Dialog,DialogContent,DialogTitle,DialogDescription} from '@/components/ui/dialog';
import {Checkbox} from '@/components/ui/checkbox';
import {AlertDialog,AlertDialogContent,AlertDialogTitle,AlertDialogDescription,AlertDialogFooter,AlertDialogCancel,AlertDialogAction} from '@/components/ui/alert-dialog';
export function Pick({label,value,onChange,items,disabled}){return <label className="field"><span>{label}</span><Select value={String(value??'')} onValueChange={onChange} disabled={disabled}><SelectTrigger className="pick"><SelectValue placeholder="Auswählen …"/></SelectTrigger><SelectContent position="popper">{items.map(x=>{let v=typeof x==='string'?x:x.value,l=typeof x==='string'?x:x.label;return <SelectItem key={String(v)} value={String(v)}>{l}</SelectItem>})}</SelectContent></Select></label>}
export function Field({label,value,onChange,type='text',...rest}){return <label className="field"><span>{label}</span><input type={type} value={value??''} onChange={e=>onChange(type==='number'?Number(e.target.value):e.target.value)} {...rest}/></label>}
export function Area({label,value,onChange,...rest}){return <label className="field"><span>{label}</span><textarea value={value||''} onChange={e=>onChange(e.target.value)} rows={4} {...rest}/></label>}
export function Check({label,checked,onChange}){return <label className="check"><Checkbox checked={checked} onCheckedChange={v=>onChange(v===true)}/><span>{label}</span></label>}
export function Modal({open,onClose,title,description,children}){return <Dialog open={open} onOpenChange={v=>!v&&onClose()}><DialogContent className="modal"><DialogTitle>{title}</DialogTitle><DialogDescription>{description||'Änderungen mit den untenstehenden Schaltflächen übernehmen.'}</DialogDescription>{children}</DialogContent></Dialog>}
export function Confirm({value,onClose}){return <AlertDialog open={!!value} onOpenChange={v=>!v&&onClose()}><AlertDialogContent><AlertDialogTitle>{value?.title||'Wirklich löschen?'}</AlertDialogTitle><AlertDialogDescription>{value?.text||'Du kannst vorher eine Sicherung exportieren.'}</AlertDialogDescription><AlertDialogFooter><AlertDialogCancel onClick={onClose}>Abbrechen</AlertDialogCancel><AlertDialogAction onClick={()=>{value?.action();onClose()}}>Bestätigen</AlertDialogAction></AlertDialogFooter></AlertDialogContent></AlertDialog>}
const inline=t=>String(t).split(/(\*\*[^*]+\*\*)/g).map((s,i)=>s.startsWith('**')?<strong key={i}>{s.slice(2,-2)}</strong>:s);
export function Text({text}){let lines=String(text||'').split('\n'),out=[];for(let i=0;i<lines.length;i++){let l=lines[i];if(l.startsWith('|')){let rows=[];while(i<lines.length&&lines[i].startsWith('|')){if(!/^\|[\s|:-]+\|$/.test(lines[i]))rows.push(lines[i].split('|').slice(1,-1));i++}i--;out.push(<div className="table-scroll" key={i}><table><tbody>{rows.map((r,j)=><tr key={j}>{r.map((v,k)=>j===0?<th key={k}>{inline(v)}</th>:<td key={k}>{inline(v)}</td>)}</tr>)}</tbody></table></div>)}else if(l.startsWith('#'))out.push(<h3 key={i}>{l.replace(/^#+\s*/,'')}</h3>);else if(l.trim())out.push(<p key={i}>{inline(l.replace(/^>\s*/,''))}</p>)}return <div className="rule-text">{out}</div>}
export function Metrics({items}){return <div className="metrics">{items.map(([k,v])=><div key={k}><span>{k}</span><strong>{v}</strong></div>)}</div>}
export function download(data,name,type='application/json'){const u=URL.createObjectURL(data instanceof Blob?data:new Blob([data],{type}));let a=document.createElement('a');a.href=u;a.download=name;a.click();setTimeout(()=>URL.revokeObjectURL(u),1000)}
